source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RJCircularCollectionViewLayout_Example', :exclusive => true do
  pod "RJCircularCollectionViewLayout", :path => "../"
end

target 'RJCircularCollectionViewLayout_Tests', :exclusive => true do
  pod "RJCircularCollectionViewLayout", :path => "../"

  
end
